TPD-1278 New Registrations Questions Look
bvcms/bvcms pull request #1016
Opened 2020-08-16 23:46 UTC by davidcarroll

2020-09-14 18:47 UTC, brondavies commented on CmsData/Registration/AskInstruction2.cs
> +	public class AskInstruction2 : Ask
@davidcarroll Will you rename this everywhere to AskInstructionPlain - so that it's more clear how it's different?

2020-09-14 18:58 UTC, brondavies commented on CmsShared/CmsShared.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
This line should have `Version="4.2.0.0"`  The nuget package installer has it wrong.

2020-09-14 18:59 UTC, brondavies commented on CmsShared/app.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
This one too should replace `4.1.1.3` with `4.2.0.0`

2020-09-14 18:59 UTC, brondavies commented on CmsTwilio/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
Same

2020-09-14 18:59 UTC, brondavies commented on CmsTwilio/CmsTwilio.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
This reference too.

2020-09-14 19:12 UTC, brondavies commented on CmsWeb/Areas/OnlineReg/Views/OnlineReg/Index.cshtml
> +        width100 {
I think you meant `.width100`

2020-09-14 19:12 UTC, brondavies commented on CmsWeb/Areas/OnlineReg/Views/OnlineReg/TestQuestions.cshtml
> +        width100 {
same here

2020-09-14 19:15 UTC, brondavies commented on CmsWeb/Areas/Org/Views/Org/DisplayTemplates/AskChurch.cshtml
> +        @Html.DisplayFor(m => m.Member, "MockCheckbox")
Will you rename `MockCheckbox.cshtml` to `DisabledCheckbox.cshtml` please?

2020-09-14 19:16 UTC, brondavies commented on CmsWeb/Areas/Org/Views/Org/DisplayTemplates/AskCoaching.cshtml
> +        @Html.DisplayFor(m => m.Interested, "MockYesNo")
Also rename `MockYesNo` to `DisabledYesNo`

2020-09-14 19:17 UTC, brondavies commented on CmsWeb/Areas/Org/Views/Org/DisplayTemplates/AskDoctor.cshtml
> +        @Html.DisplayFor(m => m.Doctor, "MockString")
`MockString.cshtml` rename to `DisabledString.cshtml`

2020-09-14 19:21 UTC, brondavies commented on CmsWeb/Code/SmartBinder.cs
> +                return Ask.NewAsk(type);
👍 Nice!

2020-09-14 19:23 UTC, brondavies commented on CmsWeb/Views/Shared/EditorTemplates/Boolean.cshtml.orig
> +﻿@model bool
You can delete this file

2020-09-14 19:24 UTC, brondavies commented on CmsWeb/Views/Shared/EditorTemplates/Decimal.cshtml.orig
> +﻿@model decimal?
Delete this file

2020-09-14 19:25 UTC, brondavies commented on CmsWeb/Web.config
> +    <add key="UseRuntimeSettingsCache" value="false" />
Probably want to remove this line.  It's normally only used in tests.

2020-09-14 19:26 UTC, brondavies commented on RepairOrg/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
Revert to `4.2.0.0` here too

2020-09-14 19:26 UTC, brondavies commented on RepairOrg/RepairOrg.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Revert to `4.2.0.0` here too

2020-09-14 19:27 UTC, brondavies commented on TransactionGateway/TransactionGateway.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Revert to `4.2.0.0` here too

2020-09-14 19:27 UTC, brondavies commented on TransactionGateway/app.config
> +                <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
Revert to `4.2.0.0` here too

2020-09-14 19:27 UTC, brondavies commented on UnitTests/CmsDataTests/CmsDataTests.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Revert to `4.2.0.0` here too

2020-09-14 19:29 UTC, brondavies requested changes
Just a few simple things.

2020-09-14 20:12 UTC, davidcarroll commented on RepairOrg/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
According to Nuget.org, there is no 4.2 anywhere, there is a 4.1 and a 4.3

2020-09-14 20:23 UTC, davidcarroll commented on CmsData/Registration/AskInstruction2.cs
> +	public class AskInstruction2 : Ask
This will break existing testing registrations by the way

2020-09-16 14:06 UTC, brondavies commented on CmsData/Classes/OnlineRegSummaryText/Details2.xml
> +      <tr><td style='{{LabelStyle}}'>Menu</td><td style='{{DataLabelStyle}}'>{{Label}}</td></tr>
There's a merge issue here with an extra column

2020-09-16 14:08 UTC, brondavies commented on CmsData/CmsData.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
This should be `Version="4.2.0.0"`

2020-09-16 14:12 UTC, brondavies commented on CmsWeb/CMSWeb.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Wrong version

2020-09-16 14:22 UTC, brondavies commented on RepairOrg/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
I know, but the 4.3.4 package assembly version is using the incorrect 4.2 version and this binding redirect will cause issues when it can't find 4.1.1.3

2020-09-16 14:38 UTC, davidcarroll commented on CmsWeb/CMSWeb.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
I don't know how to fix it, I uninstalled it with nuget then reinstalled and I still get this (note the HintPath which shows 4.3.4. That is just what Nuget put in there.
```    
<Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll</HintPath>
      <Private>True</Private>
      <Private>True</Private>
    </Reference>
```

2020-09-16 14:39 UTC, davidcarroll commented on CmsData/CmsData.csproj
> +    <Reference Include="System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
There is no 4.2 in Nuget

2020-09-16 15:09 UTC, davidcarroll commented on CmsData/Classes/OnlineRegSummaryText/Details2.xml
> +      <tr><td style='{{LabelStyle}}'>Menu</td><td style='{{DataLabelStyle}}'>{{Label}}</td></tr>
I cleaned this up and recommitted and pushed

2020-09-16 22:41 UTC, merged