TPD-1393 Testing email parameter for method used by batch service
bvcms/bvcms pull request #1040
Opened 2020-09-10 03:26 UTC by dahnbaez

https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1393&assignee=5e19301c85a8c90ecaca7d44

2020-09-10 14:16 UTC, josearmandohf requested changes
Can you add the Unit/Integration tests required?

2020-09-10 14:16 UTC, josearmandohf commented on CmsData/Email/Emailer.cs
>                  SendEmail(from,
Please Add a unit test for SendEmail()

2020-09-10 14:16 UTC, josearmandohf commented on CmsData/Email/Emailer.cs
> +                        SendEmail(from, subject, ex.Message, Util.ToMailAddressList(from), testEmail: isTestEmail);
Same here

2020-09-10 14:17 UTC, josearmandohf requested changes
Please add a unit test for...

SendEmail(from, subject, ex.Message, Util.ToMailAddressList(from), testEmail: isTestEmail);

2020-09-25 16:49 UTC, brondavies approved these changes

2020-09-25 16:49 UTC, merged