TPD-1394 Member Export Fix
bvcms/bvcms pull request #1041
Opened 2020-09-10 19:10 UTC by josearmandohf

Updating CurrOrgMembers2 function.
Only one migration file.

2020-10-05 14:14 UTC, dahnbaez requested changes

2020-10-05 14:14 UTC, dahnbaez commented on CmsWeb/Models/HomeModel.cs
> +
It seems that CodeFactor detects this switch structure as a complex method. Perhaps we can put these queries into methods to avoid this CodeFactor warning.

2020-10-05 19:09 UTC, josearmandohf commented on CmsWeb/Models/HomeModel.cs
> +
Thanks Danny, actually the intention of this method was to encapsulate the queries happening before in FastSearch method directly. What makes CodeFactor take this as a complex method was the use of the conditional operator "?:". I've updated that to be simple if conditions and that seems to do the magic with codefactor.

2020-10-05 19:58 UTC, dahnbaez approved these changes

2020-10-06 13:49 UTC, brondavies commented on UnitTests/SharedTestFixtures/MockPeople.cs
> +            if (family.IsNotNull())
family should really only be deleted if there are no people in the family. Use PurgePerson first and then check for `family.People.Count`

2020-10-06 13:55 UTC, josearmandohf commented on UnitTests/SharedTestFixtures/MockPeople.cs
> +            if (family.IsNotNull())
Thanks @brondavies working on it...

2020-10-07 18:21 UTC, merged