TPD-1372 ReCheck SMS Sent Status
bvcms/bvcms pull request #1075
Opened 2020-10-02 14:45 UTC by dahnbaez

https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&selectedIssue=TPD-1372&assignee=5e19301c85a8c90ecaca7d44

2020-10-02 14:53 UTC, brondavies approved these changes

2020-10-07 15:24 UTC, josearmandohf requested changes
Can you add unit tests?

2020-10-19 22:24 UTC, josearmandohf requested changes

2020-10-19 22:24 UTC, josearmandohf commented on UnitTests/CmsDataTests/Classes/Twilio/TwilioHelperTests.cs
> +            TwilioHelper.ProcessQueue(db, 1);
This test does not assert anything. 

The ProcessQueue() method uses an iListID parameter that then help to get a list of SMSLists DB objects. If Process is successful then at the end in TwillioHelper class Line 314 smsList.Sent is set to true.

You should be asserting smsList.Sent = true. 

An Idea is to fetch or create a list of SMSLists and the SelectFirstOrDefault(), then pass that as iListID to execute and then assert. Something like the following...

var smslist = db.SMSLists.FirstOrDefault();
TwilioHelper.ProcessQueue(db, smslist.ID)
smsList.Sent.ShouldBe(False);

2020-10-19 23:27 UTC, josearmandohf approved these changes
Approved

2020-10-21 21:38 UTC, merged