TPD-1348 Divisions Dialog Rework
bvcms/bvcms pull request #1117
Opened 2020-10-22 05:28 UTC by jason-rice

lots of work done, looking great so far! lots more to do

2020-11-03 18:39 UTC, brondavies requested changes

2020-11-03 18:39 UTC, brondavies commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +        public JsonResult GetProgramsDivisionsForOrganizationArray(int orgId)
Why not use this method for the StringArray also?

2020-11-03 18:39 UTC, brondavies commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +                        ></i>
These icons should each be wrapped in an `<a>` tag to make it function like a clickable element, preferably also with a `btn btn-link` class

2020-11-03 18:39 UTC, brondavies commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +                        ></i>
Hide the up arrow when it's the first in the list and hide the down arrow when it's the last item

2020-11-03 18:39 UTC, brondavies commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +                    <th style="width: 12%"></th>
Use a fixed `px` width on the first and last column

2020-11-04 17:24 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +                    var divName = item.Division.IsNotNull() ? item.Division.Name : "(no division)";
changed

2020-11-04 20:08 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +            }
changed this

2020-11-04 20:13 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +            }
that's awesome! changed this

2020-11-04 20:16 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +        }
very clever! changed this

2020-11-04 20:31 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +                    CurrentDatabase.DivOrgs.InsertOnSubmit(newDivOrg);
So I tried this change, but it didn't work. I did clean up this block of code though!

2020-11-04 20:32 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +                    CurrentDatabase.SubmitChanges();
Great catch! thanks

2020-11-04 20:34 UTC, jason-rice commented on CmsWeb/Areas/Org/Views/Org/Settings/Main.cshtml
> +@*<link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css">*@
oops, fixed this

2020-11-04 20:49 UTC, jason-rice commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +      }
not 100% sure why, but using just push wasn't working, but now it is, so changed this too

2020-11-04 20:51 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +        public JsonResult GetProgramsDivisionsForOrganizationStringArray(int orgId)
changed this

2020-11-04 20:51 UTC, jason-rice commented on CmsWeb/Areas/Org/Controllers/Org/OrgController.cs
> +        public JsonResult GetProgramsDivisionsForOrganizationArray(int orgId)
yeah, good point, I changed this

2020-11-04 21:49 UTC, jason-rice commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +                        ></i>
made these changes, good suggestions!

2020-11-04 23:20 UTC, jason-rice commented on CmsWeb/src/components/Modals/OrgDivAssignment.vue
> +                    <th style="width: 12%"></th>
changed this

2020-11-09 17:42 UTC, merged