TPD-1611 Delete Giving Pages
bvcms/bvcms pull request #1156
Opened 2020-11-06 22:59 UTC by jason-rice

done

2020-11-09 21:57 UTC, brondavies requested changes

2020-11-09 21:57 UTC, brondavies commented on CmsWeb/src/components/Giving/GivingManagement/GivingPageIndex.vue
> +}
This is something that should apply the same style everywhere and not just in this component

2020-11-09 21:57 UTC, brondavies commented on CmsWeb/Areas/Giving/Controllers/GivingManagementController.cs
> -        [HttpPost]
We should probably keep the `HttpPost` designation if that's how this is accessed

2020-11-09 23:31 UTC, jason-rice commented on CmsWeb/src/components/Giving/GivingManagement/GivingPageIndex.vue
> +}
deleted this

2020-11-09 23:36 UTC, jason-rice commented on CmsWeb/Areas/Giving/Controllers/GivingManagementController.cs
> -        [HttpPost]
put this attribute back

2020-11-10 01:02 UTC, josearmandohf approved these changes
Changes required were addressed.

2020-11-10 18:19 UTC, merged