TPD-1702 ManageGiving OneTimeLink Fix
bvcms/bvcms pull request #1185
Opened 2020-12-01 16:23 UTC by dahnbaez

https://touchpointsoftware.atlassian.net/browse/TPD-1702?atlOrigin=eyJpIjoiOTFmMzczZjI2ZWZkNDQyYWFjNWYwYjQ5NGNjNTdlNTQiLCJwIjoiaiJ9

2020-12-01 16:34 UTC, josearmandohf requested changes
Can you please add in the test what happened if PeopleID equals null?

2020-12-01 16:34 UTC, josearmandohf commented on CmsWeb/Areas/OnlineReg/Models/OnlineReg/CreateAccount.cs
> +                Querystring = $"{divid ?? orgid ?? masterorgid},{peopleId}"
Have you tested the variable Querystring when sending peopleID as null? 
like Querystring = = $"{divid ?? orgid ?? masterorgid},{**NULL**}"

2020-12-01 16:34 UTC, josearmandohf commented on UnitTests/CMSWebTests/Areas/OnlineReg/Models/OnlineReg/OnlineRegPersonModelTests.cs
> +            model.SendOneTimeLink("admin@example.com", "/OnlineReg/ManageGiving/", "this is a test", "{first}, this is only a test {url}", peopleId : person.PeopleId);
can you add after line 42 a model with peopleID = NULL?

2020-12-03 21:19 UTC, brondavies approved these changes

2020-12-08 18:38 UTC, merged